### PR TITLE
Update for Solax X1 & X3 Hybrid Inverters

### PR DESCRIPTION
**Pull request by asuweb**
Extensive update for Solax Hybrid inverters.  

Additional update to provide for file based (YAML) configuration. 

Solves #27 

Answers #24 #23

### CODE REVIEW

**Comment by lesma** [comment]
@asuweb Just tried this out on my G4 and have a number of missing entities on the configure page

Global Stats:
sensor.solax_grid_export_total
sensor.solax_grid_import_total
sensor.solax_battery_input_energy_total
sensor.solax_battery_output_energy_total

select.octopus_flux_export_tariff
sensor.octopus_flux_export_tariff_flux
sensor.octopus_flux_export_tariff_offpeak
sensor.octopus_flux_export_tariff_peak
select.octopus_flux_tariff
sensor.octopus_flux_tariff_flux
sensor.octopus_flux_tariff_offpeak
sensor.octopus_flux_tariff_peak

**Comment by asuweb** [comment]
@lesma 

Can you confirm which inverter you have? 

```
Global Stats:
sensor.solax_grid_export_total
sensor.solax_grid_import_total
sensor.solax_battery_input_energy_total
sensor.solax_battery_output_energy_total
```

These entities are exposed on the inverter I have (X1-Hybrid-G4).  Have a look in solax-modbus integration for similar entities.  It's also possible the entities are hidden or disabled, please check.

As for the octopus entities, I'll create them.  They are also used by the original project but not listed in the setup so I didn't include them in this PR, but I can amend that in a few days

**Comment by lesma** [comment]
@asuweb thanks for the information. 

Odd about those global stats, I too have a X1 Hybrid G4 (running ARM 2.03 DSP 2.07) about 10 days old. While I can see these stats on the invertor itself, they do not come through the integration (disabled and if I force enabled there is no data for them). 

Can’t see anything similar really, though I guess should be able to work out battery output of it using total solar energy and total yield, others might be tricky though.
Know its not your issues but can I ask what version of the firmware you are using?

**Comment by asuweb** [comment]
@lesma.  I'll check versions tomorrow.

What method are you using to connect to modbus? Pocket WiFi or rs485?

**Comment by lesma** [comment]
@asuweb  thanks, using rs485 via waveshare

**Comment by lesma** [comment]
@asuweb OK so now I geel a bit silly, just needed to wait a bit longer after enabling those sensors. Sorry for any trouble I caused you!

**Comment by lesma** [comment]
@asuweb  Can you tell me what the issue with the previous "today house load "calulation was. Looks as if it should have been correct so wondering what I am missing.

**Comment by asuweb** [comment]
Assumung you mean the templated calculation that i used. I noticed on a good solar day when battery charging that it was actually reducing the daily load when charging from solar. So I was ending up negative daily load on occasions

**Pull request merged**
